[2023-10-16T21:38:06.358-0500] {processor.py:157} INFO - Started process (PID=6231) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:38:06.358-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:38:06.359-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:38:06.359-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:38:06.362-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:38:06.362-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:38:06.363-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:38:06.362-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:38:06.363-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:38:06.371-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2023-10-16T21:38:53.591-0500] {processor.py:157} INFO - Started process (PID=6363) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:38:53.593-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:38:53.594-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:38:53.593-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:38:53.599-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:38:53.598-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:38:53.599-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:38:53.599-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:38:53.600-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:38:53.612-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-10-16T21:39:39.902-0500] {processor.py:157} INFO - Started process (PID=6468) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:39:39.903-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:39:39.903-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:39:39.903-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:39:39.905-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:39:39.905-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:39:39.906-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:39:39.906-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:39:39.906-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:39:39.912-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-10-16T21:40:30.446-0500] {processor.py:157} INFO - Started process (PID=6597) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:40:30.447-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:40:30.449-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:40:30.449-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:40:30.453-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:40:30.452-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:40:30.454-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:40:30.454-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:40:30.454-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:40:30.467-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-10-16T21:41:15.880-0500] {processor.py:157} INFO - Started process (PID=6713) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:41:15.883-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:41:15.884-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:41:15.884-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:41:15.889-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:41:15.888-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:41:15.890-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:41:15.889-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:41:15.890-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:41:15.902-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-16T21:42:02.146-0500] {processor.py:157} INFO - Started process (PID=6821) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:42:02.148-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:42:02.149-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:42:02.148-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:42:02.151-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:42:02.151-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:42:02.151-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:42:02.151-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:42:02.152-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:42:02.159-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-10-16T21:42:44.801-0500] {processor.py:157} INFO - Started process (PID=6973) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:42:44.803-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:42:44.804-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:42:44.804-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:42:44.808-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:42:44.807-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:42:44.808-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:42:44.808-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:42:44.808-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:42:44.817-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-10-16T21:43:31.634-0500] {processor.py:157} INFO - Started process (PID=7072) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:43:31.635-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:43:31.637-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:43:31.636-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:43:31.641-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:43:31.640-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:43:31.641-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:43:31.641-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:43:31.642-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:43:31.652-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-10-16T21:44:19.738-0500] {processor.py:157} INFO - Started process (PID=7172) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:44:19.740-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:44:19.741-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:44:19.741-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:44:19.744-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:44:19.743-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:44:19.744-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:44:19.744-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:44:19.744-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:44:19.753-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-10-16T21:45:04.997-0500] {processor.py:157} INFO - Started process (PID=7285) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:45:04.999-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:45:04.999-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:45:04.999-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:45:05.002-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:45:05.001-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:45:05.003-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:45:05.003-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:45:05.003-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:45:05.010-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-10-16T21:45:49.789-0500] {processor.py:157} INFO - Started process (PID=7386) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:45:49.792-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:45:49.794-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:45:49.793-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:45:49.802-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:45:49.801-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:45:49.803-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:45:49.802-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:45:49.803-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:45:49.815-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-10-16T21:46:34.379-0500] {processor.py:157} INFO - Started process (PID=7469) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:46:34.381-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:46:34.382-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:46:34.381-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:46:34.384-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:46:34.384-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:46:34.385-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:46:34.384-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:46:34.385-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:46:34.393-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2023-10-16T21:47:21.039-0500] {processor.py:157} INFO - Started process (PID=7558) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:47:21.043-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:47:21.045-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:47:21.044-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:47:21.052-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:47:21.051-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:47:21.053-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:47:21.052-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:47:21.053-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:47:21.065-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T21:48:11.027-0500] {processor.py:157} INFO - Started process (PID=7652) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:48:11.027-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:48:11.028-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:48:11.028-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:48:11.030-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:48:11.029-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:48:11.030-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:48:11.030-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:48:11.030-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:48:11.036-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-10-16T21:49:00.016-0500] {processor.py:157} INFO - Started process (PID=7736) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:49:00.017-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:49:00.018-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:49:00.018-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:49:00.023-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:49:00.022-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:49:00.023-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:49:00.023-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:49:00.023-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:49:00.032-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-10-16T21:49:48.661-0500] {processor.py:157} INFO - Started process (PID=7841) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:49:48.663-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:49:48.664-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:49:48.664-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:49:48.672-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:49:48.670-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:49:48.672-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:49:48.672-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:49:48.673-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:49:48.686-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-10-16T21:50:40.428-0500] {processor.py:157} INFO - Started process (PID=7949) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:50:40.430-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:50:40.432-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:50:40.431-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:50:40.439-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:50:40.438-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:50:40.440-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:50:40.440-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:50:40.440-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:50:40.453-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T21:51:34.157-0500] {processor.py:157} INFO - Started process (PID=8045) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:51:34.159-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:51:34.160-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:51:34.160-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:51:34.163-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:51:34.162-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:51:34.163-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:51:34.163-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:51:34.163-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:51:34.172-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2023-10-16T21:52:28.768-0500] {processor.py:157} INFO - Started process (PID=8161) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:52:28.771-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:52:28.772-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:52:28.771-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:52:28.775-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:52:28.774-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:52:28.775-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:52:28.775-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:52:28.775-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:52:28.783-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2023-10-16T21:53:15.930-0500] {processor.py:157} INFO - Started process (PID=8287) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:53:15.932-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:53:15.935-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:53:15.934-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:53:15.942-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:53:15.941-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:53:15.943-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:53:15.942-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:53:15.943-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:53:15.957-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T21:54:05.900-0500] {processor.py:157} INFO - Started process (PID=8374) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:54:05.901-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:54:05.903-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:54:05.902-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:54:05.909-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:54:05.907-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:54:05.909-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:54:05.909-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:54:05.910-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:54:05.923-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-10-16T21:54:59.192-0500] {processor.py:157} INFO - Started process (PID=8469) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:54:59.195-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:54:59.197-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:54:59.196-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:54:59.205-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:54:59.203-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:54:59.206-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:54:59.205-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:54:59.206-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:54:59.222-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-10-16T21:55:50.068-0500] {processor.py:157} INFO - Started process (PID=8580) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:55:50.072-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:55:50.074-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:55:50.073-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:55:50.080-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:55:50.079-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:55:50.081-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:55:50.081-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:55:50.082-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:55:50.094-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-10-16T21:56:40.675-0500] {processor.py:157} INFO - Started process (PID=8668) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:56:40.677-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:56:40.678-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:56:40.677-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:56:40.681-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:56:40.680-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:56:40.681-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:56:40.681-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:56:40.681-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:56:40.691-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2023-10-16T21:57:30.765-0500] {processor.py:157} INFO - Started process (PID=8774) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:57:30.769-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:57:30.771-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:57:30.770-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:57:30.779-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:57:30.777-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:57:30.780-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:57:30.780-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:57:30.781-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:57:30.795-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-10-16T21:58:19.645-0500] {processor.py:157} INFO - Started process (PID=8866) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:58:19.649-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:58:19.651-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:58:19.650-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:58:19.658-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:58:19.656-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:58:19.658-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:58:19.658-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:58:19.659-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:58:19.671-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-10-16T21:59:14.165-0500] {processor.py:157} INFO - Started process (PID=8983) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:59:14.167-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T21:59:14.170-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:59:14.169-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:59:14.181-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:59:14.178-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T21:59:14.181-0500] {logging_mixin.py:151} INFO - [2023-10-16T21:59:14.181-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T21:59:14.182-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T21:59:14.206-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-10-16T22:00:05.807-0500] {processor.py:157} INFO - Started process (PID=9113) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:00:05.809-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:00:05.811-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:00:05.810-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:00:05.814-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:00:05.813-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:00:05.815-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:00:05.814-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:00:05.815-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:00:05.825-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-10-16T22:00:58.572-0500] {processor.py:157} INFO - Started process (PID=9222) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:00:58.575-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:00:58.577-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:00:58.576-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:00:58.585-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:00:58.583-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:00:58.585-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:00:58.585-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:00:58.586-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:00:58.604-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-10-16T22:01:49.107-0500] {processor.py:157} INFO - Started process (PID=9304) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:01:49.109-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:01:49.110-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:01:49.110-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:01:49.115-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:01:49.114-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:01:49.115-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:01:49.115-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:01:49.116-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:01:49.129-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-16T22:02:42.975-0500] {processor.py:157} INFO - Started process (PID=9401) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:02:42.979-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:02:42.981-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:02:42.980-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:02:42.989-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:02:42.987-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:02:42.990-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:02:42.990-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:02:42.991-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:02:43.007-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-10-16T22:03:31.083-0500] {processor.py:157} INFO - Started process (PID=9493) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:03:31.086-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:03:31.089-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:03:31.088-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:03:31.099-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:03:31.097-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:03:31.100-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:03:31.099-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:03:31.100-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:03:31.116-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-10-16T22:04:17.664-0500] {processor.py:157} INFO - Started process (PID=9575) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:04:17.668-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:04:17.670-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:04:17.669-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:04:17.678-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:04:17.676-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:04:17.678-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:04:17.678-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:04:17.679-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:04:17.691-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T22:05:07.041-0500] {processor.py:157} INFO - Started process (PID=9660) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:05:07.042-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:05:07.044-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:05:07.043-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:05:07.050-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:05:07.048-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:05:07.050-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:05:07.050-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:05:07.051-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:05:07.066-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-10-16T22:05:51.858-0500] {processor.py:157} INFO - Started process (PID=9754) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:05:51.860-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:05:51.860-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:05:51.860-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:05:51.863-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:05:51.862-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:05:51.863-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:05:51.863-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:05:51.863-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:05:51.869-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:06:38.563-0500] {processor.py:157} INFO - Started process (PID=9842) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:06:38.565-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:06:38.566-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:06:38.565-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:06:38.568-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:06:38.567-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:06:38.568-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:06:38.568-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:06:38.568-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:06:38.575-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:07:24.967-0500] {processor.py:157} INFO - Started process (PID=9924) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:07:24.971-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:07:24.973-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:07:24.972-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:07:24.980-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:07:24.979-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:07:24.981-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:07:24.980-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:07:24.981-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:07:24.994-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T22:08:12.462-0500] {processor.py:157} INFO - Started process (PID=10009) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:08:12.465-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:08:12.468-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:08:12.467-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:08:12.476-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:08:12.474-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:08:12.477-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:08:12.476-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:08:12.477-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:08:12.491-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-10-16T22:09:04.071-0500] {processor.py:157} INFO - Started process (PID=10098) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:09:04.073-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:09:04.074-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:09:04.074-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:09:04.076-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:09:04.076-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:09:04.076-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:09:04.076-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:09:04.076-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:09:04.083-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:09:50.457-0500] {processor.py:157} INFO - Started process (PID=10182) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:09:50.459-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:09:50.461-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:09:50.460-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:09:50.466-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:09:50.464-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:09:50.466-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:09:50.466-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:09:50.466-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:09:50.481-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-10-16T22:10:37.518-0500] {processor.py:157} INFO - Started process (PID=10265) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:10:37.521-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:10:37.521-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:10:37.521-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:10:37.524-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:10:37.524-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:10:37.525-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:10:37.525-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:10:37.525-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:10:37.534-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-10-16T22:11:28.850-0500] {processor.py:157} INFO - Started process (PID=10351) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:11:28.852-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:11:28.852-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:11:28.852-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:11:28.854-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:11:28.854-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:11:28.855-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:11:28.855-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:11:28.855-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:11:28.861-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:12:15.064-0500] {processor.py:157} INFO - Started process (PID=10433) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:12:15.066-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:12:15.068-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:12:15.067-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:12:15.072-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:12:15.072-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:12:15.073-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:12:15.072-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:12:15.073-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:12:15.079-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2023-10-16T22:13:02.707-0500] {processor.py:157} INFO - Started process (PID=10517) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:13:02.708-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:13:02.709-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:13:02.709-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:13:02.711-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:13:02.711-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:13:02.712-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:13:02.711-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:13:02.712-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:13:02.718-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:13:54.315-0500] {processor.py:157} INFO - Started process (PID=10613) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:13:54.319-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:13:54.321-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:13:54.320-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:13:54.329-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:13:54.328-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:13:54.330-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:13:54.330-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:13:54.330-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:13:54.344-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-10-16T22:14:45.070-0500] {processor.py:157} INFO - Started process (PID=10698) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:14:45.074-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:14:45.076-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:14:45.075-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:14:45.085-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:14:45.083-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:14:45.086-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:14:45.086-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:14:45.087-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:14:45.101-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-10-16T22:15:34.238-0500] {processor.py:157} INFO - Started process (PID=10786) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:15:34.238-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:15:34.239-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:15:34.239-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:15:34.241-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:15:34.241-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:15:34.241-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:15:34.241-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:15:34.242-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:15:34.248-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:16:25.940-0500] {processor.py:157} INFO - Started process (PID=10881) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:16:25.940-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:16:25.941-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:16:25.941-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:16:25.943-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:16:25.942-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:16:25.943-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:16:25.943-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:16:25.943-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:16:25.949-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-10-16T22:17:13.589-0500] {processor.py:157} INFO - Started process (PID=10966) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:17:13.592-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:17:13.594-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:17:13.594-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:17:13.601-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:17:13.599-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:17:13.601-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:17:13.601-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:17:13.602-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:17:13.619-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T22:18:03.430-0500] {processor.py:157} INFO - Started process (PID=11062) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:18:03.433-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:18:03.435-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:18:03.435-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:18:03.443-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:18:03.441-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:18:03.444-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:18:03.444-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:18:03.445-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:18:03.461-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-10-16T22:18:55.301-0500] {processor.py:157} INFO - Started process (PID=11163) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:18:55.304-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:18:55.307-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:18:55.306-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:18:55.314-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:18:55.312-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:18:55.314-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:18:55.314-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:18:55.315-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:18:55.326-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-10-16T22:19:45.395-0500] {processor.py:157} INFO - Started process (PID=11248) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:19:45.397-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:19:45.399-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:19:45.398-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:19:45.407-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:19:45.405-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:19:45.408-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:19:45.407-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:19:45.408-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:19:45.425-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-10-16T22:20:33.463-0500] {processor.py:157} INFO - Started process (PID=11338) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:20:33.467-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:20:33.470-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:20:33.468-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:20:33.478-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:20:33.476-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:20:33.479-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:20:33.478-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:20:33.479-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:20:33.497-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-10-16T22:21:26.289-0500] {processor.py:157} INFO - Started process (PID=11430) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:21:26.292-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:21:26.296-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:21:26.294-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:21:26.305-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:21:26.303-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:21:26.306-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:21:26.305-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:21:26.306-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:21:26.320-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-10-16T22:22:14.376-0500] {processor.py:157} INFO - Started process (PID=11519) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:22:14.378-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:22:14.378-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:22:14.378-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:22:14.381-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:22:14.380-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:22:14.381-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:22:14.381-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:22:14.381-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:22:14.387-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:23:04.181-0500] {processor.py:157} INFO - Started process (PID=11606) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:23:04.183-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:23:04.185-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:23:04.184-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:23:04.193-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:23:04.191-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:23:04.194-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:23:04.194-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:23:04.195-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:23:04.214-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-10-16T22:23:58.137-0500] {processor.py:157} INFO - Started process (PID=11702) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:23:58.139-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:23:58.139-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:23:58.139-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:23:58.142-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:23:58.141-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:23:58.142-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:23:58.142-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:23:58.142-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:23:58.149-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:24:45.003-0500] {processor.py:157} INFO - Started process (PID=11820) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:24:45.005-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:24:45.006-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:24:45.005-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:24:45.008-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:24:45.007-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:24:45.008-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:24:45.008-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:24:45.008-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:24:45.015-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:25:33.979-0500] {processor.py:157} INFO - Started process (PID=11926) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:25:33.980-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:25:33.980-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:25:33.980-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:25:33.983-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:25:33.982-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:25:33.983-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:25:33.983-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:25:33.983-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:25:33.989-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-10-16T22:26:23.018-0500] {processor.py:157} INFO - Started process (PID=12030) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:26:23.020-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:26:23.022-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:26:23.021-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:26:23.028-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:26:23.027-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:26:23.029-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:26:23.028-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:26:23.029-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:26:23.040-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-10-16T22:27:14.712-0500] {processor.py:157} INFO - Started process (PID=12150) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:27:14.713-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:27:14.714-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:27:14.714-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:27:14.718-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:27:14.717-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:27:14.718-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:27:14.718-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:27:14.718-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:27:14.728-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-10-16T22:28:07.065-0500] {processor.py:157} INFO - Started process (PID=12267) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:28:07.067-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:28:07.068-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:28:07.068-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:28:07.074-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:28:07.073-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:28:07.074-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:28:07.074-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:28:07.075-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:28:07.089-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-10-16T22:29:00.264-0500] {processor.py:157} INFO - Started process (PID=12369) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:29:00.268-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:29:00.270-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:29:00.269-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:29:00.278-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:29:00.276-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:29:00.278-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:29:00.278-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:29:00.279-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:29:00.293-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-10-16T22:29:46.888-0500] {processor.py:157} INFO - Started process (PID=12452) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:29:46.889-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:29:46.890-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:29:46.889-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:29:46.892-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:29:46.892-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:29:46.893-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:29:46.893-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:29:46.893-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:29:46.900-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:30:36.608-0500] {processor.py:157} INFO - Started process (PID=12563) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:30:36.612-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:30:36.614-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:30:36.613-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:30:36.622-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:30:36.621-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:30:36.623-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:30:36.623-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:30:36.623-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:30:36.637-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-10-16T22:31:23.686-0500] {processor.py:157} INFO - Started process (PID=12642) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:31:23.688-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:31:23.689-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:31:23.688-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:31:23.692-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:31:23.691-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:31:23.692-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:31:23.692-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:31:23.692-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:31:23.700-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2023-10-16T22:32:11.001-0500] {processor.py:157} INFO - Started process (PID=12736) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:32:11.003-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:32:11.004-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:32:11.003-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:32:11.006-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:32:11.005-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:32:11.006-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:32:11.006-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:32:11.006-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:32:11.014-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-10-16T22:33:04.075-0500] {processor.py:157} INFO - Started process (PID=12879) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:33:04.078-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:33:04.080-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:33:04.080-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:33:04.088-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:33:04.086-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:33:04.089-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:33:04.089-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:33:04.089-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:33:04.106-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-10-16T22:33:57.823-0500] {processor.py:157} INFO - Started process (PID=13190) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:33:57.825-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:33:57.826-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:33:57.826-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:33:57.828-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:33:57.827-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:33:57.828-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:33:57.828-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:33:57.828-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:33:57.835-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:34:44.294-0500] {processor.py:157} INFO - Started process (PID=13312) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:34:44.295-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:34:44.295-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:34:44.295-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:34:44.298-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:34:44.297-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:34:44.298-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:34:44.298-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:34:44.298-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:34:44.305-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:35:34.992-0500] {processor.py:157} INFO - Started process (PID=13449) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:35:34.995-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:35:34.998-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:35:34.997-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:35:35.006-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:35:35.004-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:35:35.007-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:35:35.007-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:35:35.008-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:35:35.028-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-10-16T22:36:27.915-0500] {processor.py:157} INFO - Started process (PID=13932) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:36:27.916-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:36:27.917-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:36:27.916-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:36:27.919-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:36:27.918-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:36:27.919-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:36:27.919-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:36:27.919-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:36:27.926-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:37:22.186-0500] {processor.py:157} INFO - Started process (PID=14355) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:37:22.188-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:37:22.190-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:37:22.189-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:37:22.198-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:37:22.196-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:37:22.198-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:37:22.198-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:37:22.199-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:37:22.214-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-10-16T22:38:13.552-0500] {processor.py:157} INFO - Started process (PID=14465) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:38:13.554-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:38:13.556-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:38:13.555-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:38:13.564-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:38:13.562-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:38:13.565-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:38:13.564-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:38:13.565-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:38:13.580-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-10-16T22:39:03.947-0500] {processor.py:157} INFO - Started process (PID=14778) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:39:03.948-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:39:03.948-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:39:03.948-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:39:03.951-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:39:03.950-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:39:03.951-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:39:03.951-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:39:03.951-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:39:03.957-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-10-16T22:39:50.830-0500] {processor.py:157} INFO - Started process (PID=14868) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:39:50.832-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:39:50.834-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:39:50.833-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:39:50.839-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:39:50.838-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:39:50.839-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:39:50.839-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:39:50.839-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:39:50.845-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2023-10-16T22:40:41.180-0500] {processor.py:157} INFO - Started process (PID=15018) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:40:41.182-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:40:41.183-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:40:41.183-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:40:41.186-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:40:41.186-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:40:41.187-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:40:41.187-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:40:41.187-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:40:41.194-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2023-10-16T22:41:27.242-0500] {processor.py:157} INFO - Started process (PID=15121) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:41:27.246-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:41:27.249-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:41:27.248-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:41:27.257-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:41:27.255-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:41:27.257-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:41:27.257-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:41:27.258-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:41:27.271-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-10-16T22:42:18.675-0500] {processor.py:157} INFO - Started process (PID=15253) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:42:18.676-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:42:18.677-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:42:18.677-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:42:18.682-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:42:18.681-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:42:18.682-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:42:18.682-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:42:18.683-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:42:18.693-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-10-16T22:43:05.818-0500] {processor.py:157} INFO - Started process (PID=15358) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:43:05.819-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:43:05.820-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:43:05.820-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:43:05.822-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:43:05.822-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:43:05.822-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:43:05.822-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:43:05.822-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:43:05.829-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:43:55.753-0500] {processor.py:157} INFO - Started process (PID=15453) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:43:55.754-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:43:55.755-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:43:55.754-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:43:55.758-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:43:55.757-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:43:55.758-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:43:55.758-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:43:55.758-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:43:55.770-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-10-16T22:44:44.789-0500] {processor.py:157} INFO - Started process (PID=15584) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:44:44.791-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:44:44.792-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:44:44.792-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:44:44.797-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:44:44.796-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:44:44.797-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:44:44.797-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:44:44.798-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:44:44.810-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-16T22:45:34.178-0500] {processor.py:157} INFO - Started process (PID=15694) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:45:34.178-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:45:34.179-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:45:34.179-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:45:34.181-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:45:34.181-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:45:34.182-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:45:34.182-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:45:34.182-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:45:34.188-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-10-16T22:46:27.899-0500] {processor.py:157} INFO - Started process (PID=15805) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:46:27.902-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:46:27.904-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:46:27.903-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:46:27.908-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:46:27.907-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:46:27.909-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:46:27.909-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:46:27.909-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:46:27.922-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-10-16T22:47:19.505-0500] {processor.py:157} INFO - Started process (PID=15909) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:47:19.508-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:47:19.509-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:47:19.509-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:47:19.514-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:47:19.513-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:47:19.515-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:47:19.515-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:47:19.515-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:47:19.526-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-10-16T22:48:14.164-0500] {processor.py:157} INFO - Started process (PID=16036) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:48:14.167-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:48:14.169-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:48:14.168-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:48:14.173-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:48:14.172-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:48:14.173-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:48:14.173-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:48:14.173-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:48:14.183-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-10-16T22:49:01.960-0500] {processor.py:157} INFO - Started process (PID=16147) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:49:01.962-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:49:01.963-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:49:01.963-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:49:01.968-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:49:01.966-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:49:01.968-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:49:01.968-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:49:01.968-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:49:01.977-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-10-16T22:50:09.888-0500] {processor.py:157} INFO - Started process (PID=16312) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:50:09.890-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:50:09.890-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:50:09.890-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:50:09.893-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:50:09.892-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:50:09.893-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:50:09.893-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:50:09.893-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:50:09.900-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-10-16T22:51:02.320-0500] {processor.py:157} INFO - Started process (PID=16430) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:51:02.321-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:51:02.322-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:51:02.321-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:51:02.325-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:51:02.324-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:51:02.326-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:51:02.325-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:51:02.326-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:51:02.336-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-10-16T22:51:47.213-0500] {processor.py:157} INFO - Started process (PID=16514) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:51:47.213-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:51:47.214-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:51:47.214-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:51:47.217-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:51:47.216-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:51:47.217-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:51:47.217-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:51:47.217-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:51:47.225-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-10-16T22:52:37.244-0500] {processor.py:157} INFO - Started process (PID=16633) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:52:37.247-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:52:37.248-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:52:37.248-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:52:37.252-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:52:37.252-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:52:37.253-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:52:37.253-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:52:37.253-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:52:37.264-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-10-16T22:53:26.395-0500] {processor.py:157} INFO - Started process (PID=16731) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:53:26.398-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:53:26.399-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:53:26.398-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:53:26.403-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:53:26.402-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:53:26.403-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:53:26.403-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:53:26.403-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:53:26.412-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-10-16T22:54:15.085-0500] {processor.py:157} INFO - Started process (PID=16861) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:54:15.087-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:54:15.087-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:54:15.087-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:54:15.090-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:54:15.090-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:54:15.090-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:54:15.090-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:54:15.091-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:54:15.098-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-10-16T22:55:00.857-0500] {processor.py:157} INFO - Started process (PID=16977) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:55:00.859-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:55:00.860-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:55:00.859-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:55:00.862-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:55:00.862-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:55:00.862-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:55:00.862-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:55:00.862-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:55:00.870-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-10-16T22:55:48.972-0500] {processor.py:157} INFO - Started process (PID=17089) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:55:48.976-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:55:48.978-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:55:48.977-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:55:48.986-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:55:48.985-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:55:48.987-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:55:48.987-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:55:48.988-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:55:49.003-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-10-16T22:56:39.965-0500] {processor.py:157} INFO - Started process (PID=17183) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:56:39.967-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:56:39.968-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:56:39.967-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:56:39.974-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:56:39.973-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:56:39.975-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:56:39.974-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:56:39.975-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:56:39.990-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-10-16T22:57:31.943-0500] {processor.py:157} INFO - Started process (PID=17303) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:57:31.945-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:57:31.946-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:57:31.945-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:57:31.950-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:57:31.949-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:57:31.950-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:57:31.950-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:57:31.950-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:57:31.960-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-10-16T22:58:20.217-0500] {processor.py:157} INFO - Started process (PID=17401) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:58:20.220-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:58:20.222-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:58:20.221-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:58:20.230-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:58:20.228-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:58:20.231-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:58:20.231-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:58:20.232-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:58:20.256-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-10-16T22:59:08.216-0500] {processor.py:157} INFO - Started process (PID=17507) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:59:08.219-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T22:59:08.221-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:59:08.220-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:59:08.227-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:59:08.226-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T22:59:08.228-0500] {logging_mixin.py:151} INFO - [2023-10-16T22:59:08.228-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T22:59:08.228-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T22:59:08.241-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-10-16T23:00:00.642-0500] {processor.py:157} INFO - Started process (PID=17608) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:00:00.644-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T23:00:00.645-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:00:00.645-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:00:00.650-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:00:00.649-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T23:00:00.650-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:00:00.650-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T23:00:00.650-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:00:00.662-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-10-16T23:00:50.434-0500] {processor.py:157} INFO - Started process (PID=17712) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:00:50.436-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T23:00:50.437-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:00:50.437-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:00:50.441-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:00:50.440-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T23:00:50.441-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:00:50.441-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T23:00:50.441-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:00:50.449-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2023-10-16T23:01:41.011-0500] {processor.py:157} INFO - Started process (PID=17809) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:01:41.015-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T23:01:41.018-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:01:41.017-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:01:41.027-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:01:41.025-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T23:01:41.028-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:01:41.027-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T23:01:41.028-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:01:41.043-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-10-16T23:02:26.387-0500] {processor.py:157} INFO - Started process (PID=17964) to work on /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:02:26.389-0500] {processor.py:829} INFO - Processing file /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-16T23:02:26.390-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:02:26.389-0500] {dagbag.py:536} INFO - Filling up the DagBag from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:02:26.393-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:02:26.392-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-16T23:02:26.393-0500] {logging_mixin.py:151} INFO - [2023-10-16T23:02:26.393-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-16T23:02:26.393-0500] {processor.py:841} WARNING - No viable dags retrieved from /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-16T23:02:26.401-0500] {processor.py:179} INFO - Processing /home/dexne/Desktop/fault-tolerant/Airflow/venv/lib64/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
